/*
Copyright Percona LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package valkey is the operator's domain/protocol engine. In M2 it carries the
// minimal per-node client surface the ValkeyNode controller needs: connecting to
// a single live pod, reading INFO replication for the live role, and applying
// the live-settable CONFIG SET allowlist. The full CLUSTER command set and
// ClusterState land in M3.
//
// The two interfaces below are the mockable seams (see docs/architecture
// 04 §3 / 05 §10). envtest has no kubelet, so the controller's "connect to the
// live pod" path must sit behind ConfigClient / ClientFactory so tests inject a
// fake. Both are regenerated by `make generate` into mock_client.go.
package valkey

import (
	"context"

	valkeyv1alpha1 "valkey.percona.com/percona-valkey-operator/pkg/apis/valkey/v1alpha1"
)

//go:generate mockgen -destination=mock_client.go -package=valkey valkey.percona.com/percona-valkey-operator/pkg/valkey ConfigClient,ClusterClient,ClientFactory,ClusterClientFactory

// ConfigClient is the subset of Valkey operations the ValkeyNode controller
// needs: read the live replication role and apply the live-settable config
// allowlist. An interface so envtest can inject a fake (there is no live engine
// to talk to under envtest). The cluster-command surface is in ClusterClient.
type ConfigClient interface {
	// InfoReplication returns the parsed `INFO replication` map (role,
	// master_link_status, slave_repl_offset, ...). The live role is read from
	// here, never from nodeIndex (05 §10).
	InfoReplication(ctx context.Context) (map[string]string, error)
	// ConfigSet applies a single live-settable key=value via CONFIG SET. The
	// allowlist is enforced by the caller (05 §11).
	ConfigSet(ctx context.Context, key, value string) error
	// Ping issues PING for a liveness check.
	Ping(ctx context.Context) error
	// Close releases the underlying connection.
	Close() error
}

// FailoverMode selects the CLUSTER FAILOVER variant (05 §6-§7). The graceful
// (empty) mode hands off from a live primary and is used proactively before
// rolling a live primary; FORCE elects without the old primary's cooperation
// when a quorum still exists; TAKEOVER is the unilateral last-resort promotion
// used only on quorum loss with persistence off.
type FailoverMode string

const (
	// FailoverGraceful is a graceful failover that waits for the old primary to
	// hand off (no FORCE / TAKEOVER token).
	FailoverGraceful FailoverMode = ""
	// FailoverForce issues CLUSTER FAILOVER FORCE.
	FailoverForce FailoverMode = "FORCE"
	// FailoverTakeover issues CLUSTER FAILOVER TAKEOVER (last resort, 05 §7).
	FailoverTakeover FailoverMode = "TAKEOVER"
)

// SlotMigration is one entry of CLUSTER GETSLOTMIGRATIONS, the pre-check the
// controller runs before issuing a rebalance/drain move (05 §4).
type SlotMigration struct {
	// State is the migration state token (e.g. "running", "success",
	// "failed"); a non-terminal state means a move is still in flight.
	State string
	// Slots is the migrating slot range, when reported.
	Slots SlotRange
	// NodeID is the destination node ID, when reported.
	NodeID string
}

// IsTerminal reports whether the migration has reached a terminal state, so it
// no longer blocks a fresh move.
func (m SlotMigration) IsTerminal() bool {
	switch m.State {
	case "success", "failed", "canceled", "cancelled":
		return true
	default:
		return false
	}
}

// ClusterClient is the single-node command surface the PerconaValkeyCluster
// controller drives. It widens the M2 ConfigClient (GO-2.1) with the full
// CLUSTER orchestration set. All calls go over a ForceSingleClient connection
// authed as _operator with a WRONGPASS -> unauthenticated fallback (05 §10).
type ClusterClient interface {
	ConfigClient

	// Scrape — the read commands that build a NodeState (one DoMulti batch).

	// ClusterMyID returns CLUSTER MYID (this node's 40-hex node ID).
	ClusterMyID(ctx context.Context) (string, error)
	// ClusterMyShardID returns CLUSTER MYSHARDID (this node's shard ID).
	ClusterMyShardID(ctx context.Context) (string, error)
	// ClusterInfo returns raw CLUSTER INFO output.
	ClusterInfo(ctx context.Context) (string, error)
	// ClusterNodes returns raw CLUSTER NODES output.
	ClusterNodes(ctx context.Context) (string, error)
	// Info returns raw INFO output for the given section ("" for all).
	Info(ctx context.Context, section string) (string, error)

	// Orchestration — the write commands that form/heal/scale the cluster.

	// ClusterSetConfigEpoch sets this node's config epoch (bumped before MEET so
	// a joining node has authority above any dead node it replaces, 05 §3).
	ClusterSetConfigEpoch(ctx context.Context, epoch int64) error
	// ClusterMeet introduces this node to a peer at ip:port with its bus port
	// (05 §3). The operator issues MEET bidirectionally.
	ClusterMeet(ctx context.Context, ip string, port, busPort int) error
	// ClusterAddSlotsRange assigns the given slot ranges to this primary
	// (05 §3, only on zero-slot primaries for idempotency).
	ClusterAddSlotsRange(ctx context.Context, ranges []SlotRange) error
	// ClusterReplicate makes this node a replica of primaryID (05 §3).
	ClusterReplicate(ctx context.Context, primaryID string) error
	// ClusterMigrateSlots atomically migrates the given ranges to dstID
	// (CLUSTER MIGRATESLOTS, Valkey 9.0+, 05 §4).
	ClusterMigrateSlots(ctx context.Context, ranges []SlotRange, dstID string) error
	// ClusterGetSlotMigrations returns the in-progress/terminal migrations
	// (CLUSTER GETSLOTMIGRATIONS, 05 §4).
	ClusterGetSlotMigrations(ctx context.Context) ([]SlotMigration, error)
	// ClusterForget removes nodeID from this node's gossip table
	// (CLUSTER FORGET, 05 §7).
	ClusterForget(ctx context.Context, nodeID string) error
	// ClusterFailover issues CLUSTER FAILOVER in the given mode (05 §6-§7).
	ClusterFailover(ctx context.Context, mode FailoverMode) error
}

// ClientFactory is the seam the ValkeyNode controller holds so envtest injects a
// fake. For resolves the _operator password from the node's cluster
// ACL/system-passwords Secret, builds the <status.podIP>:6379 address and the
// TLS config from spec.tls, then dials via NewClient (05 §10). It is what
// OPS-2.4 mocks; its For() returns a ConfigClient (itself mockable for
// status/liveconfig tests).
type ClientFactory interface {
	For(ctx context.Context, node *valkeyv1alpha1.ValkeyNode) (ConfigClient, error)
}

// ClusterClientFactory is the seam the PerconaValkeyCluster controller holds so
// envtest injects a scripted fake (CR-18: there is no live Valkey under
// envtest). ForNode resolves the _operator credential + TLS from the cluster's
// Secrets, builds the <status.podIP>:6379 address and dials a ClusterClient —
// the full CLUSTER orchestration surface the cluster controller drives during
// bootstrap (MEET/ADDSLOTSRANGE/REPLICATE/...). Distinct from ClientFactory so
// the cluster loop gets the wide surface while the node loop keeps the narrow
// ConfigClient.
type ClusterClientFactory interface {
	// ForNode dials the node's live pod and returns its ClusterClient. The addr
	// is returned alongside so the caller can key the scraped NodeState by the
	// dial address it actually connected to (05 §10).
	ForNode(ctx context.Context, node *valkeyv1alpha1.ValkeyNode) (addr string, c ClusterClient, err error)
}
