// Code generated by MockGen. DO NOT EDIT.
// Source: valkey.percona.com/percona-valkey-operator/pkg/valkey (interfaces: ConfigClient,ClusterClient,ClientFactory,ClusterClientFactory)
//
// Generated by this command:
//
//	mockgen -destination=pkg/valkey/mock_client.go -package=valkey valkey.percona.com/percona-valkey-operator/pkg/valkey ConfigClient,ClusterClient,ClientFactory,ClusterClientFactory
//

// Package valkey is a generated GoMock package.
package valkey

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1alpha1 "valkey.percona.com/percona-valkey-operator/pkg/apis/valkey/v1alpha1"
)

// MockConfigClient is a mock of ConfigClient interface.
type MockConfigClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfigClientMockRecorder
	isgomock struct{}
}

// MockConfigClientMockRecorder is the mock recorder for MockConfigClient.
type MockConfigClientMockRecorder struct {
	mock *MockConfigClient
}

// NewMockConfigClient creates a new mock instance.
func NewMockConfigClient(ctrl *gomock.Controller) *MockConfigClient {
	mock := &MockConfigClient{ctrl: ctrl}
	mock.recorder = &MockConfigClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigClient) EXPECT() *MockConfigClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConfigClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConfigClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConfigClient)(nil).Close))
}

// ConfigSet mocks base method.
func (m *MockConfigClient) ConfigSet(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigSet", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigSet indicates an expected call of ConfigSet.
func (mr *MockConfigClientMockRecorder) ConfigSet(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigSet", reflect.TypeOf((*MockConfigClient)(nil).ConfigSet), ctx, key, value)
}

// InfoReplication mocks base method.
func (m *MockConfigClient) InfoReplication(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoReplication", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InfoReplication indicates an expected call of InfoReplication.
func (mr *MockConfigClientMockRecorder) InfoReplication(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoReplication", reflect.TypeOf((*MockConfigClient)(nil).InfoReplication), ctx)
}

// Ping mocks base method.
func (m *MockConfigClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockConfigClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockConfigClient)(nil).Ping), ctx)
}

// MockClusterClient is a mock of ClusterClient interface.
type MockClusterClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientMockRecorder
	isgomock struct{}
}

// MockClusterClientMockRecorder is the mock recorder for MockClusterClient.
type MockClusterClientMockRecorder struct {
	mock *MockClusterClient
}

// NewMockClusterClient creates a new mock instance.
func NewMockClusterClient(ctrl *gomock.Controller) *MockClusterClient {
	mock := &MockClusterClient{ctrl: ctrl}
	mock.recorder = &MockClusterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClient) EXPECT() *MockClusterClientMockRecorder {
	return m.recorder
}

// ACLList mocks base method.
func (m *MockClusterClient) ACLList(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ACLList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ACLList indicates an expected call of ACLList.
func (mr *MockClusterClientMockRecorder) ACLList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ACLList", reflect.TypeOf((*MockClusterClient)(nil).ACLList), ctx)
}

// ACLLoad mocks base method.
func (m *MockClusterClient) ACLLoad(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ACLLoad", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ACLLoad indicates an expected call of ACLLoad.
func (mr *MockClusterClientMockRecorder) ACLLoad(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ACLLoad", reflect.TypeOf((*MockClusterClient)(nil).ACLLoad), ctx)
}

// Close mocks base method.
func (m *MockClusterClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClusterClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClusterClient)(nil).Close))
}

// ClusterAddSlotsRange mocks base method.
func (m *MockClusterClient) ClusterAddSlotsRange(ctx context.Context, ranges []SlotRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterAddSlotsRange", ctx, ranges)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterAddSlotsRange indicates an expected call of ClusterAddSlotsRange.
func (mr *MockClusterClientMockRecorder) ClusterAddSlotsRange(ctx, ranges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterAddSlotsRange", reflect.TypeOf((*MockClusterClient)(nil).ClusterAddSlotsRange), ctx, ranges)
}

// ClusterFailover mocks base method.
func (m *MockClusterClient) ClusterFailover(ctx context.Context, mode FailoverMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterFailover", ctx, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterFailover indicates an expected call of ClusterFailover.
func (mr *MockClusterClientMockRecorder) ClusterFailover(ctx, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterFailover", reflect.TypeOf((*MockClusterClient)(nil).ClusterFailover), ctx, mode)
}

// ClusterForget mocks base method.
func (m *MockClusterClient) ClusterForget(ctx context.Context, nodeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterForget", ctx, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterForget indicates an expected call of ClusterForget.
func (mr *MockClusterClientMockRecorder) ClusterForget(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterForget", reflect.TypeOf((*MockClusterClient)(nil).ClusterForget), ctx, nodeID)
}

// ClusterGetSlotMigrations mocks base method.
func (m *MockClusterClient) ClusterGetSlotMigrations(ctx context.Context) ([]SlotMigration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterGetSlotMigrations", ctx)
	ret0, _ := ret[0].([]SlotMigration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterGetSlotMigrations indicates an expected call of ClusterGetSlotMigrations.
func (mr *MockClusterClientMockRecorder) ClusterGetSlotMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterGetSlotMigrations", reflect.TypeOf((*MockClusterClient)(nil).ClusterGetSlotMigrations), ctx)
}

// ClusterInfo mocks base method.
func (m *MockClusterClient) ClusterInfo(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterInfo", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterInfo indicates an expected call of ClusterInfo.
func (mr *MockClusterClientMockRecorder) ClusterInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterInfo", reflect.TypeOf((*MockClusterClient)(nil).ClusterInfo), ctx)
}

// ClusterMeet mocks base method.
func (m *MockClusterClient) ClusterMeet(ctx context.Context, ip string, port, busPort int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterMeet", ctx, ip, port, busPort)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterMeet indicates an expected call of ClusterMeet.
func (mr *MockClusterClientMockRecorder) ClusterMeet(ctx, ip, port, busPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterMeet", reflect.TypeOf((*MockClusterClient)(nil).ClusterMeet), ctx, ip, port, busPort)
}

// ClusterMigrateSlots mocks base method.
func (m *MockClusterClient) ClusterMigrateSlots(ctx context.Context, ranges []SlotRange, dstID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterMigrateSlots", ctx, ranges, dstID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterMigrateSlots indicates an expected call of ClusterMigrateSlots.
func (mr *MockClusterClientMockRecorder) ClusterMigrateSlots(ctx, ranges, dstID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterMigrateSlots", reflect.TypeOf((*MockClusterClient)(nil).ClusterMigrateSlots), ctx, ranges, dstID)
}

// ClusterMyID mocks base method.
func (m *MockClusterClient) ClusterMyID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterMyID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterMyID indicates an expected call of ClusterMyID.
func (mr *MockClusterClientMockRecorder) ClusterMyID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterMyID", reflect.TypeOf((*MockClusterClient)(nil).ClusterMyID), ctx)
}

// ClusterMyShardID mocks base method.
func (m *MockClusterClient) ClusterMyShardID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterMyShardID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterMyShardID indicates an expected call of ClusterMyShardID.
func (mr *MockClusterClientMockRecorder) ClusterMyShardID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterMyShardID", reflect.TypeOf((*MockClusterClient)(nil).ClusterMyShardID), ctx)
}

// ClusterNodes mocks base method.
func (m *MockClusterClient) ClusterNodes(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterNodes", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterNodes indicates an expected call of ClusterNodes.
func (mr *MockClusterClientMockRecorder) ClusterNodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterNodes", reflect.TypeOf((*MockClusterClient)(nil).ClusterNodes), ctx)
}

// ClusterReplicate mocks base method.
func (m *MockClusterClient) ClusterReplicate(ctx context.Context, primaryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterReplicate", ctx, primaryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterReplicate indicates an expected call of ClusterReplicate.
func (mr *MockClusterClientMockRecorder) ClusterReplicate(ctx, primaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterReplicate", reflect.TypeOf((*MockClusterClient)(nil).ClusterReplicate), ctx, primaryID)
}

// ClusterSetConfigEpoch mocks base method.
func (m *MockClusterClient) ClusterSetConfigEpoch(ctx context.Context, epoch int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterSetConfigEpoch", ctx, epoch)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClusterSetConfigEpoch indicates an expected call of ClusterSetConfigEpoch.
func (mr *MockClusterClientMockRecorder) ClusterSetConfigEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterSetConfigEpoch", reflect.TypeOf((*MockClusterClient)(nil).ClusterSetConfigEpoch), ctx, epoch)
}

// ConfigSet mocks base method.
func (m *MockClusterClient) ConfigSet(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigSet", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigSet indicates an expected call of ConfigSet.
func (mr *MockClusterClientMockRecorder) ConfigSet(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigSet", reflect.TypeOf((*MockClusterClient)(nil).ConfigSet), ctx, key, value)
}

// Info mocks base method.
func (m *MockClusterClient) Info(ctx context.Context, section string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx, section)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockClusterClientMockRecorder) Info(ctx, section any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockClusterClient)(nil).Info), ctx, section)
}

// InfoReplication mocks base method.
func (m *MockClusterClient) InfoReplication(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoReplication", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InfoReplication indicates an expected call of InfoReplication.
func (mr *MockClusterClientMockRecorder) InfoReplication(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoReplication", reflect.TypeOf((*MockClusterClient)(nil).InfoReplication), ctx)
}

// Ping mocks base method.
func (m *MockClusterClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockClusterClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockClusterClient)(nil).Ping), ctx)
}

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
	isgomock struct{}
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockClientFactory) For(ctx context.Context, node *v1alpha1.ValkeyNode) (ConfigClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", ctx, node)
	ret0, _ := ret[0].(ConfigClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockClientFactoryMockRecorder) For(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockClientFactory)(nil).For), ctx, node)
}

// MockClusterClientFactory is a mock of ClusterClientFactory interface.
type MockClusterClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientFactoryMockRecorder
	isgomock struct{}
}

// MockClusterClientFactoryMockRecorder is the mock recorder for MockClusterClientFactory.
type MockClusterClientFactoryMockRecorder struct {
	mock *MockClusterClientFactory
}

// NewMockClusterClientFactory creates a new mock instance.
func NewMockClusterClientFactory(ctrl *gomock.Controller) *MockClusterClientFactory {
	mock := &MockClusterClientFactory{ctrl: ctrl}
	mock.recorder = &MockClusterClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClientFactory) EXPECT() *MockClusterClientFactoryMockRecorder {
	return m.recorder
}

// ForNode mocks base method.
func (m *MockClusterClientFactory) ForNode(ctx context.Context, node *v1alpha1.ValkeyNode) (string, ClusterClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForNode", ctx, node)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(ClusterClient)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ForNode indicates an expected call of ForNode.
func (mr *MockClusterClientFactoryMockRecorder) ForNode(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForNode", reflect.TypeOf((*MockClusterClientFactory)(nil).ForNode), ctx, node)
}
